[workspace]
resolver = "2"
members = ["crates/amz-core", "crates/amz-remote", "crates/amz-cli", "crates/amz-tunnel", "crates/amz-ipc", "crates/amz-helper", "app/src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
indexmap = { version = "2", features = ["serde"] }
