from app import proxy

# same shape as the real proxy (IPs replaced): relay rules + catch-all multiport
NAT = """# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
:DOCKER - [0:0]
-A PREROUTING -d 198.51.100.1/32 -i eth0 -p tcp -m tcp --dport 2222 -m comment --comment amnezia-ssh-2222 -j DNAT --to-destination 203.0.113.9:22
-A PREROUTING -d 198.51.100.1/32 -i eth0 -p udp -m udp --dport 48303 -m comment --comment amnezia-relay-48303 -j DNAT --to-destination 203.0.113.9:48303
-A PREROUTING -p tcp -m multiport --dports 443,8443,10000:60000 -j DNAT --to-destination 203.0.113.9
-A PREROUTING -p udp -m multiport --dports 443,8443,10000:60000 -j DNAT --to-destination 203.0.113.9
-A DOCKER -p udp -m udp --dport 5555 -j DNAT --to-destination 172.17.0.2:5555
-A POSTROUTING -d 203.0.113.9/32 -p udp -j SNAT --to-source 198.51.100.1
COMMIT
"""


def test_parse_nat():
    rules = proxy.parse_nat(NAT)
    assert len(rules) == 4  # DOCKER chain and POSTROUTING ignored
    relay = rules[1]
    assert relay["proto"] == "udp" and relay["dports"] == [(48303, 48303)]
    assert relay["to_ip"] == "203.0.113.9" and relay["to_port"] == 48303 and relay["comment"] == "amnezia-relay-48303"
    assert rules[3]["dports"] == [(443, 443), (8443, 8443), (10000, 60000)] and rules[3]["to_port"] is None
    assert not any(r["ours"] for r in rules)


def test_conflicts_and_pick_port():
    scan = {"nat": proxy.parse_nat(NAT), "udp_listen": [60001]}
    err = proxy.port_conflict(51820, scan, set())
    assert "10000:60000" in err and "203.0.113.9" in err
    assert proxy.port_conflict(2222, scan, set()) is None  # tcp rule does not block udp
    assert proxy.pick_port(scan, set()) == 60002  # 60001 is listened on
    assert proxy.pick_port(scan, {60002}) == 60003


def test_external_cascade_detection():
    servers = [
        {"id": "p", "host": "198.51.100.1", "scan": {"nat": proxy.parse_nat(NAT), "awg": None}},
        {"id": "e", "host": "203.0.113.9", "scan": {"awg": {"listen_port": 48303}}},
        {"id": "x", "host": "192.0.2.5", "scan": {"awg": {"listen_port": 40000}}},
    ]
    found = proxy.external_cascades(servers, lambda s: s["host"])
    assert found == [{"proxy_id": "p", "exit_id": "e", "port": 48303,
                      "rule": "udp 48303 → 203.0.113.9:48303 (amnezia-relay-48303)"}]


def test_catch_all_only_detected_on_same_port():
    nat = proxy.parse_nat(NAT.replace("--dport 48303", "--dport 1").replace(":48303", ":1"))
    servers = [{"id": "p", "host": "p", "scan": {"nat": nat}},
               {"id": "e", "host": "203.0.113.9", "scan": {"awg": {"listen_port": 48303}}}]
    assert proxy.external_cascades(servers, lambda s: s["host"])[0]["port"] == 48303


def test_managed_status():
    ours = "-A CASCADE_PRE -p udp -m udp --dport 60001 -j DNAT --to-destination 203.0.113.9:48303\n"
    scan = {"nat": proxy.parse_nat(NAT + ours)}
    assert proxy.managed_status({"port": 60001}, scan, "203.0.113.9") == "applied"
    assert proxy.managed_status({"port": 60005}, scan, "203.0.113.9") == "missing"
    assert proxy.managed_status({"port": 50000}, scan, "203.0.113.9") == "conflict"
    assert proxy.managed_status({"port": 60001}, None, "203.0.113.9") == "unknown"


class ProbeHost:
    """Counts UDP probes that 'arrive': `blocked` drops everything sent to this host."""
    def __init__(self, host, blocked=False):
        self.host, self.blocked, self.rules, self.arrived = host, blocked, [], 0
        self.sent = []

    def run(self, cmd, input=None, check=True, timeout=None):
        if "iptables -N" in cmd:
            self.rules.append(cmd)
            self.arrived = 0
        elif cmd.startswith("iptables -t raw -L CASCADE_PROBE"):
            return f"Chain CASCADE_PROBE (1 references)\n pkts bytes target\n {self.arrived} 100 RETURN udp\n"
        elif "/dev/udp/" in cmd:
            self.sent.append(cmd)
        return ""


def send_between(sender, receiver):
    if not receiver.blocked:
        receiver.arrived = proxy.PROBES


def test_check_link_ok_and_blocked(monkeypatch):
    monkeypatch.setattr(proxy, "PROBE_WAIT", 0)
    px, ex = ProbeHost("198.51.100.1"), ProbeHost("203.0.113.9")
    monkeypatch.setattr(proxy, "udp_reaches", lambda s, r, ip, port: (send_between(s, r), r.arrived)[1])
    log = []
    assert proxy.check_link(px, ex, "203.0.113.9", 48303, 60001, log.append) is None
    assert "дошло 5 из 5" in log[0]

    blocked = ProbeHost("203.0.113.9", blocked=True)
    log = []
    err = proxy.check_link(px, blocked, "203.0.113.9", 48303, 60001, log.append)
    assert "не доходит" in err and "0 из 5" in log[0]

    log = []  # reply path broken
    ex2 = ProbeHost("203.0.113.9")
    px_blocked = ProbeHost("198.51.100.1", blocked=True)
    err = proxy.check_link(px_blocked, ex2, "203.0.113.9", 48303, 60001, log.append)
    assert "Ответы сервера выхода не вернутся" in err


def test_probe_rules_are_counting_only_and_removed():
    calls = []

    class R:
        host = "1.2.3.4"
        def run(self, cmd, input=None, check=True, timeout=None):
            calls.append(cmd)
            return " 7 500 RETURN udp\n" if cmd.startswith("iptables -t raw -L CASCADE_PROBE") else ""

    r = R()
    proxy._probe_begin(r, "5.6.7.8", 51820)
    assert "-j RETURN" in calls[0] and "-t raw -I PREROUTING 1 -j CASCADE_PROBE" in calls[0]
    assert not any(t in calls[0] for t in ("DROP", "ACCEPT", "DNAT"))
    assert proxy._probe_end(r) == 7
    assert "-t raw -D PREROUTING -j CASCADE_PROBE" in calls[-1] and "-X CASCADE_PROBE" in calls[-1]
