//! Scenario tests of whole operations, ported from the reference panel's tests/test_api.py.
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use amz_core::model::{Server, State};
use amz_core::storage::Storage;
use amz_core::{decode_vpn_key, keys, parse_conf};
use amz_remote::ops::{self, CascadeRequest, Connector};
use amz_remote::{proxy, Remote};
use anyhow::{anyhow, bail, Result};

const PROXY_IP: &str = "198.51.100.1";
const EXIT_IP: &str = "203.0.113.9";
const EXIT2_IP: &str = "192.0.2.5";

// same shape as the real proxy (IPs replaced): relay rules + catch-all multiport
const NAT: &str = "# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
:DOCKER - [0:0]
-A PREROUTING -d 198.51.100.1/32 -i eth0 -p tcp -m tcp --dport 2222 -m comment --comment amnezia-ssh-2222 -j DNAT --to-destination 203.0.113.9:22
-A PREROUTING -d 198.51.100.1/32 -i eth0 -p udp -m udp --dport 48303 -m comment --comment amnezia-relay-48303 -j DNAT --to-destination 203.0.113.9:48303
-A PREROUTING -p tcp -m multiport --dports 443,8443,10000:60000 -j DNAT --to-destination 203.0.113.9
-A PREROUTING -p udp -m multiport --dports 443,8443,10000:60000 -j DNAT --to-destination 203.0.113.9
-A DOCKER -p udp -m udp --dport 5555 -j DNAT --to-destination 172.17.0.2:5555
-A POSTROUTING -d 203.0.113.9/32 -p udp -j SNAT --to-source 198.51.100.1
COMMIT
";

fn server_conf(priv_key: &str, port: u16) -> String {
    format!("[Interface]\nPrivateKey = {priv_key}\nAddress = 10.8.1.0/24\nListenPort = {port}\nJc = 4\nJmin = 10\nJmax = 50\n\
             S1 = 97\nS2 = 34\nH1 = 111\nH2 = 222\nH3 = 333\nH4 = 444\n\n[Peer]\nPublicKey = AAA\nPresharedKey = BBB\nAllowedIPs = 10.8.1.1/32\n")
}

/// A fake server: the proxy (NAT table built from our rules script) or an AmneziaVPN exit (container with files).
#[derive(Default)]
struct Host {
    proxy: bool,
    files: HashMap<String, String>,
    containers: Vec<String>,
    /// probes that arrive at this host
    arrived: u32,
    down: bool,
    /// overrides: command substring -> answer
    answers: Vec<(String, String)>,
    /// `docker run` starts this container
    starts: Option<String>,
}

impl Host {
    fn exit(port: u16) -> Self {
        let mut h = Host { arrived: 5, containers: vec!["amnezia-awg".into(), "amnezia-dns".into()], ..Default::default() };
        h.files.insert("/opt/amnezia/awg/wg0.conf".into(), server_conf(&keys::gen_private_key(), port));
        h.files.insert("/opt/amnezia/awg/wireguard_psk.key".into(), "SHAREDPSK\n".into());
        h
    }

    fn run(&mut self, cmd: &str, input: Option<&str>) -> Result<String> {
        if self.down {
            bail!("ssh down");
        }
        if let Some((_, a)) = self.answers.iter().find(|(k, _)| cmd.contains(k.as_str())) {
            return Ok(a.clone());
        }
        if cmd.starts_with("iptables -t raw -L CASCADE_PROBE") {
            return Ok(format!(" {} 100 RETURN udp\n", self.arrived));
        }
        if let Some(rest) = cmd.strip_prefix("cat > ") {
            let path = rest.split(" && ").next().unwrap().trim_matches('\'');
            let path = path.replace("/opt/cascade-awg-v3", "/opt/cascade");
            self.files.insert(path, input.unwrap_or_default().into());
            return Ok(String::new());
        }
        if self.proxy {
            if cmd.starts_with("iptables-save") {
                let script = self.files.get(proxy::SCRIPT_PATH).cloned().unwrap_or_default();
                let ours: Vec<String> = script.lines().filter(|l| l.starts_with("iptables -t nat -A CASCADE_PRE"))
                    .map(|l| l.replace("iptables -t nat -A", "-A")).collect();
                return Ok(format!("{NAT}{}\n", ours.join("\n")));
            }
            return Ok(String::new());
        }
        if cmd.starts_with("command -v docker >/dev/null && echo yes") {
            return Ok("yes\n".into());
        }
        if cmd.starts_with("command -v docker") {
            return Ok(self.containers.join("\n") + "\n");
        }
        if cmd.contains("docker run") {
            self.containers.extend(self.starts.clone());
            return Ok(String::new());
        }
        if cmd.starts_with("docker exec -i ") {
            let inner = shlex::split(cmd).unwrap().pop().unwrap();
            if inner.starts_with("ls ") {
                return Ok("/opt/amnezia/awg/wg0.conf\n".into());
            }
            if inner.starts_with("command -v awg") {
                return Ok("wg\n".into());
            }
            let words: Vec<&str> = inner.split_whitespace().collect();
            if inner.starts_with("cat >> ") {
                self.files.get_mut(words[2]).unwrap().push_str(input.unwrap());
                return Ok(String::new());
            }
            if inner.starts_with("cat > ") {
                self.files.insert(words[2].into(), input.unwrap().into());
                return Ok(String::new());
            }
            if inner.starts_with("cat ") {
                return Ok(self.files.get(words[1]).cloned().unwrap_or_default());
            }
        }
        Ok(String::new())
    }
}

type Hosts = Arc<HashMap<String, Arc<Mutex<Host>>>>;

struct FakeRemote {
    host: String,
    h: Arc<Mutex<Host>>,
}

impl Remote for FakeRemote {
    fn host(&self) -> &str {
        &self.host
    }
    async fn exec(&mut self, cmd: &str, input: Option<&str>, _check: bool, _t: Duration) -> Result<String> {
        self.h.lock().unwrap().run(cmd, input)
    }
    async fn reconnect(&mut self) -> Result<()> {
        Ok(())
    }
}

struct FakeConn(Hosts);

impl Connector for FakeConn {
    type R = FakeRemote;
    async fn connect(&self, s: &Server) -> Result<FakeRemote> {
        let h = self.0.get(&s.host).ok_or_else(|| anyhow!("no host {}", s.host))?.clone();
        Ok(FakeRemote { host: s.host.clone(), h })
    }
    fn ip_of(&self, s: &Server) -> String {
        s.host.clone()
    }
}

struct Env {
    conn: FakeConn,
    store: Storage,
    s: State,
    ids: HashMap<&'static str, String>,
    _dir: TempDir,
}

struct TempDir(std::path::PathBuf);
impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

impl Env {
    fn host(&self, ip: &str) -> std::sync::MutexGuard<'_, Host> {
        self.conn.0[ip].lock().unwrap()
    }
    fn file(&self, ip: &str, path: &str) -> String {
        self.host(ip).files.get(path).cloned().unwrap_or_default()
    }
    fn cascade_req(&self, exits: &[&str], port: Option<u16>, instance: &str) -> CascadeRequest {
        CascadeRequest { proxy_id: self.ids["proxy"].clone(), exit_ids: exits.iter().map(|e| self.ids[e].clone()).collect(),
                         port, instance: instance.into() }
    }
}

async fn setup(scan: bool) -> Env {
    tokio::time::pause();
    let mut exit = Host::exit(48303);
    exit.arrived = 5;
    let hosts: HashMap<String, Arc<Mutex<Host>>> = [
        (PROXY_IP, Host { proxy: true, arrived: 5, ..Default::default() }),
        (EXIT_IP, exit),
        (EXIT2_IP, Host::exit(43210)),
    ].into_iter().map(|(k, v)| (k.to_string(), Arc::new(Mutex::new(v)))).collect();
    let dir = std::env::temp_dir().join(format!("amz-ops-{}", ops::new_id()));
    let mut env = Env { conn: FakeConn(Arc::new(hosts)), store: Storage::new(&dir), s: State::default(),
                        ids: HashMap::new(), _dir: TempDir(dir) };
    for (name, host) in [("proxy", PROXY_IP), ("praga", EXIT_IP), ("nl", EXIT2_IP)] {
        let id = ops::new_id();
        env.s.servers.push(Server { id: id.clone(), name: name.into(), host: host.into(), ssh_port: 22,
                                    user: "root".into(), ..Default::default() });
        env.ids.insert(name, id.clone());
        if scan {
            ops::scan_server(&env.conn, &env.store, &mut env.s, &id).await.unwrap();
        }
    }
    env
}

async fn adopt_praga_and_add_client(env: &mut Env) -> (String, String) {
    let (p, e) = (env.ids["proxy"].clone(), env.ids["praga"].clone());
    ops::adopt_cascade(&env.conn, &env.store, &mut env.s, &p, &e, 48303).unwrap();
    let cid = env.s.cascades[0].id.clone();
    let made = ops::create_clients(&env.conn, &env.store, &mut env.s, "phone", std::slice::from_ref(&cid)).await.unwrap();
    (cid, made[0].clone())
}

#[tokio::test]
async fn existing_cascade_is_highlighted_and_adoptable() {
    let mut env = setup(true).await;
    let ext = ops::external_not_adopted(&env.conn, &env.s);
    assert_eq!(ext.len(), 1);
    assert_eq!((ext[0].port, ext[0].rule.as_str()), (48303, "udp 48303 → 203.0.113.9:48303 (amnezia-relay-48303)"));

    let (_, client) = adopt_praga_and_add_client(&mut env).await;
    assert!(ops::external_not_adopted(&env.conn, &env.s).is_empty());
    assert_eq!(ops::cascade_views(&env.conn, &env.s)[0].status, "external");
    assert!(!env.host(PROXY_IP).files.contains_key(proxy::SCRIPT_PATH)); // nothing written to the proxy
    let r = ops::render(&env.s, &client).unwrap();
    assert!(r.conf.contains("Endpoint = 198.51.100.1:48303"));
    assert!(r.conf.contains("Address = 10.8.1.2/32") && r.conf.contains("PresharedKey = SHAREDPSK"));
    assert_eq!(r.filename, "phone_proxy_praga.conf");
    // the saved file matches what is in memory
    assert_eq!(env.store.load().unwrap(), env.s);
}

#[tokio::test]
async fn managed_cascade_avoids_existing_ports() {
    let mut env = setup(true).await;
    let r = { let req = env.cascade_req(&["nl"], Some(51820), "auto"); ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await };
    assert!(!r.ok && r.log.last().unwrap().contains("10000:60000"), "{:?}", r.log);
    assert!(!env.host(PROXY_IP).files.contains_key(proxy::SCRIPT_PATH));

    let r = { let req = env.cascade_req(&["nl", "praga"], None, ""); ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await };
    assert!(r.ok, "{:?}", r.log);
    assert!(r.log.iter().any(|l| l.contains("уже есть существующий каскад"))); // praga already relayed via 48303
    let script = env.file(PROXY_IP, proxy::SCRIPT_PATH);
    assert!(script.contains("--dport 60001 -j DNAT --to-destination 192.0.2.5:43210"), "{script}");
    assert!(script.contains("--dport 60002 -j DNAT --to-destination 203.0.113.9:48303"));
    let views = ops::cascade_views(&env.conn, &env.s);
    assert_eq!(views.iter().map(|v| v.status.as_str()).collect::<Vec<_>>(), ["applied", "applied"]);

    let cids: Vec<String> = env.s.cascades.iter().map(|c| c.id.clone()).collect();
    let made = ops::create_clients(&env.conn, &env.store, &mut env.s, "phone", &cids).await.unwrap();
    let doc = decode_vpn_key(&ops::render(&env.s, &made[0]).unwrap().vpn_key).unwrap();
    assert_eq!(doc["hostName"], PROXY_IP);
    assert_eq!(doc["containers"][0]["awg"]["port"], "60001");

    // one key with both exits: the chosen one is the default, the other is in our extension
    let (_, exits) = ops::render_all(&env.s, &made[1]).unwrap();
    assert_eq!(exits.iter().map(|e| e.name.as_str()).collect::<Vec<_>>(), ["praga", "nl"]);
    let imported = amz_core::import_vpn_key(&ops::render_all(&env.s, &made[1]).unwrap().0.vpn_key).unwrap();
    assert_eq!((imported.name.as_str(), imported.exits.len()), ("phone", 2));
    assert!(imported.conf.contains(":60002") && imported.exits[1].conf.contains(":60001"));

    let r = ops::delete_cascade(&env.conn, &env.store, &mut env.s, &cids[0]).await;
    assert!(r.ok, "{:?}", r.log);
    let script = env.file(PROXY_IP, proxy::SCRIPT_PATH);
    assert!(!script.contains("60001") && script.contains("60002"));
    assert_eq!(env.s.clients.len(), 1);
}

#[tokio::test]
async fn cascade_refused_when_udp_blocked() {
    let mut env = setup(true).await;
    env.host(EXIT2_IP).arrived = 0;
    let r = { let req = env.cascade_req(&["nl"], None, "auto"); ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await };
    assert!(!r.ok && r.log.last().unwrap().contains("не доходит"), "{:?}", r.log);
    assert!(!env.host(PROXY_IP).files.contains_key(proxy::SCRIPT_PATH));
    assert!(env.s.cascades.is_empty());
}

#[tokio::test]
async fn delete_client_revokes_peer_or_keeps_it_when_server_fails() {
    let mut env = setup(true).await;
    let (cid, made) = adopt_praga_and_add_client(&mut env).await;
    assert!(env.file(EXIT_IP, "/opt/amnezia/awg/wg0.conf").contains("10.8.1.2/32"));
    let r = ops::delete_client(&env.conn, &env.store, &mut env.s, &made).await;
    assert!(r.ok && r.log[0].contains("отозван"), "{:?}", r.log);
    assert!(!env.file(EXIT_IP, "/opt/amnezia/awg/wg0.conf").contains("10.8.1.2/32"));
    assert!(env.s.clients.is_empty());
    assert!(!ops::delete_client(&env.conn, &env.store, &mut env.s, &made).await.ok);

    let made = ops::create_clients(&env.conn, &env.store, &mut env.s, "phone", &[cid]).await.unwrap();
    env.host(EXIT_IP).down = true;
    let r = ops::delete_client(&env.conn, &env.store, &mut env.s, &made[0]).await;
    assert!(!r.ok && r.log.last().unwrap().contains("ssh down"));
    assert_eq!(env.s.clients.len(), 1); // not lost from the list
}

#[tokio::test]
async fn traffic_accumulates_and_survives_counter_reset() {
    let mut env = setup(true).await;
    let (_, made) = adopt_praga_and_add_client(&mut env).await;
    let pubkey = env.s.clients[0].public_key.clone();
    let set = |env: &Env, rx: u64, tx: u64| {
        env.host(EXIT_IP).answers = vec![
            ("show wg0 transfer".into(), format!("{pubkey}\t{rx}\t{tx}\nOTHERKEY\t5\t5\n")),
            ("show wg0 latest-handshakes".into(), format!("{pubkey}\t1790000000\n")),
        ];
    };
    set(&env, 1000, 2000);
    let r = ops::refresh_traffic(&env.conn, &env.store, &mut env.s).await;
    assert!(r.ok && r.log == ["praga: обновлено клиентов 1"], "{:?}", r.log);
    let c = &env.s.clients[0];
    assert_eq!((c.traffic.unwrap().rx, c.traffic.unwrap().tx, c.handshake), (1000, 2000, Some(1790000000)));
    assert!(c.stats_at.is_some() && c.id == made);

    set(&env, 1500, 2500); // more traffic
    ops::refresh_traffic(&env.conn, &env.store, &mut env.s).await;
    assert_eq!(env.s.clients[0].traffic, Some(amz_core::model::Traffic { rx: 1500, tx: 2500 }));

    set(&env, 100, 200); // interface restarted: counters start over
    ops::refresh_traffic(&env.conn, &env.store, &mut env.s).await;
    assert_eq!(env.s.clients[0].traffic, Some(amz_core::model::Traffic { rx: 1600, tx: 2700 }));

    env.host(EXIT_IP).down = true;
    let r = ops::refresh_traffic(&env.conn, &env.store, &mut env.s).await;
    assert!(!r.ok && r.log[0].contains("ssh down"), "{:?}", r.log);
    assert_eq!(env.s.clients[0].traffic, Some(amz_core::model::Traffic { rx: 1600, tx: 2700 })); // kept as is
}

#[tokio::test]
async fn cascade_with_awg3_container() {
    let mut env = setup(true).await;
    {
        let mut h = env.host(EXIT2_IP);
        h.containers.clear();
        h.starts = Some("cascade-awg-v3".into());
        h.answers.push(("iptables -t nat -S POSTROUTING".into(), "-A POSTROUTING -s 10.9.3.0/24 -o eth0 -j MASQUERADE\n".into()));
    }
    // the container reports the port it was started with
    let conn_hosts = env.conn.0.clone();
    let waiter = tokio::spawn(async move {
        loop {
            tokio::time::sleep(Duration::from_millis(100)).await;
            let mut h = conn_hosts[EXIT2_IP].lock().unwrap();
            if let Some(conf) = h.files.get("/opt/cascade/awgv3.conf").cloned() {
                let lp = parse_conf(&conf).0["ListenPort"].clone();
                h.answers.push(("awg show awgv3 listen-port".into(), lp));
                break;
            }
        }
    });
    let r = { let req = env.cascade_req(&["nl"], None, "v3"); ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await };
    waiter.await.unwrap();
    assert!(r.ok, "{:?}", r.log);
    let v = ops::cascade_views(&env.conn, &env.s).into_iter().find(|v| v.cascade.exit_id == env.ids["nl"]).unwrap();
    assert_eq!((v.cascade.instance(), v.awg_version.as_deref()), ("v3", Some("3.x")));
    let made = ops::create_clients(&env.conn, &env.store, &mut env.s, "laptop", std::slice::from_ref(&v.cascade.id)).await.unwrap();
    let conf = ops::render(&env.s, &made[0]).unwrap().conf;
    assert!(conf.contains("Address = 10.9.3.2/32") && conf.contains("HeaderProtectionKey = "), "{conf}");
    assert!(!env.file(EXIT2_IP, "/opt/amnezia/awg/wg0.conf").contains("10.9.3.2")); // main instance untouched
}

#[tokio::test]
async fn legacy_request_reuses_main_awg_1_0() {
    let mut env = setup(false).await;
    let r = { let req = env.cascade_req(&["nl"], None, "legacy"); ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await };
    assert!(r.ok, "{:?}", r.log);
    assert!(r.log.iter().any(|l| l.contains("уже версии 1.0")));
    assert_eq!(env.s.cascades[0].instance(), "main");
    let r = { let req = env.cascade_req(&["nl"], None, "legacy"); ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await };
    assert!(r.ok && r.log.iter().any(|l| l.contains("каскад уже есть")), "{:?}", r.log);
    // first SSH connection remembers nothing for fakes, and rejected requests keep the state file valid
    assert_eq!(env.store.load().unwrap(), env.s);
}

#[tokio::test]
async fn bad_requests_are_refused() {
    let mut env = setup(false).await;
    let proxy_as_exit = env.cascade_req(&["proxy"], None, "auto");
    for (req, msg) in [
        (env.cascade_req(&[], None, "auto"), "хотя бы один"),
        (proxy_as_exit, "сам для себя"),
        (env.cascade_req(&["nl", "praga"], Some(51820), "auto"), "только для одного"),
        (env.cascade_req(&["nl"], None, "v9"), "Неизвестная версия"),
    ] {
        let r = ops::create_cascades(&env.conn, &env.store, &mut env.s, &req).await;
        assert!(!r.ok && r.log.last().unwrap().contains(msg), "{:?}", r.log);
    }
    assert_eq!(ops::clean_name("  Мама <script>!  "), "Мама script");
    assert_eq!(ops::clean_name("!!!"), "client");
    let e = env.ids["nl"].clone();
    let p = env.ids["proxy"].clone();
    assert!(ops::adopt_cascade(&env.conn, &env.store, &mut env.s, &p, &e, 1).is_err());
}

#[tokio::test]
async fn direct_connection_without_proxy() {
    let mut env = setup(true).await;
    let praga = env.ids["praga"].clone();
    let r = ops::create_direct(&env.conn, &env.store, &mut env.s, &praga, "auto").await;
    assert!(r.ok && r.log.last().unwrap().contains("UDP 48303"), "{:?}", r.log);
    let cid = ops::direct_of(&env.s, &praga, "main").unwrap();
    assert!(ops::create_direct(&env.conn, &env.store, &mut env.s, &praga, "auto").await.log.last().unwrap().contains("уже есть"));
    assert_eq!(ops::cascade_views(&env.conn, &env.s)[0].status, "direct");
    assert!(ops::check_cascade(&env.conn, &mut env.s, &cid).await.ok);

    // the client connects straight to the server's own AmneziaWG
    let made = ops::create_clients(&env.conn, &env.store, &mut env.s, "laptop", std::slice::from_ref(&cid)).await.unwrap();
    assert!(ops::render(&env.s, &made[0]).unwrap().conf.contains(&format!("Endpoint = {EXIT_IP}:48303")));
    assert!(!env.host(PROXY_IP).files.contains_key(proxy::SCRIPT_PATH));

    let r = ops::delete_cascade(&env.conn, &env.store, &mut env.s, &cid).await;
    assert!(r.ok && env.s.cascades.is_empty() && env.s.clients.is_empty(), "{:?}", r.log);
}
