"""Foreign (exit) AmneziaWG server: detect existing setup, install if missing, add client peers."""
import ipaddress
import json
import random
import shlex
import time
from datetime import datetime, timezone

from . import configs, keys
from .ssh import Remote

AMNEZIA_DIR = "/opt/amnezia/awg"
NATIVE_CONF = "/etc/amnezia/amneziawg/awg0.conf"
NATIVE_SUBNET = "10.8.0.1/24"
POLL_SECONDS = 5

# AmneziaWG instances we run ourselves, each in its own container with userspace amneziawg-go.
# The host kernel and an existing AmneziaVPN container are never touched.
# "legacy" keeps the names of the first implementation so already deployed instances keep working.
INSTANCES = {
    "legacy": {"container": "cascade-awg-legacy", "dir": "/opt/cascade-awg-legacy", "iface": "awgl0",
               "subnet": "10.9.0.1/24", "version": "v1", "label": "AmneziaWG 1.0 (роутеры)"},
    "v2": {"container": "cascade-awg-v2", "dir": "/opt/cascade-awg-v2", "iface": "awgv2",
           "subnet": "10.9.2.1/24", "version": "v2", "label": "AmneziaWG 2.0"},
    "v3": {"container": "cascade-awg-v3", "dir": "/opt/cascade-awg-v3", "iface": "awgv3",
           "subnet": "10.9.3.1/24", "version": "v3", "label": "AmneziaWG 3.x"},
}
# pinned on purpose: this build runs 1.0/2.0/3.x configs, newer images may change defaults
AWG_IMAGE = "amneziavpn/amneziawg-go:3.1.20260828"
AWG1_KEYS = {"jc", "jmin", "jmax", "s1", "s2", "h1", "h2", "h3", "h4"}


def start_script(inst: dict) -> str:
    net = ipaddress.ip_interface(inst["subnet"]).network
    return f"""#!/bin/sh
# generated by vpn_service: {inst['label']}
awg-quick down /opt/cascade/{inst['iface']}.conf 2>/dev/null
awg-quick up /opt/cascade/{inst['iface']}.conf
iptables -A FORWARD -i {inst['iface']} -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -t nat -A POSTROUTING -s {net} -o eth0 -j MASQUERADE
exec tail -f /dev/null
"""


def rx(r: Remote, info: dict, cmd: str, input: str | None = None, check: bool = True) -> str:
    """Run cmd inside the Amnezia container (if any) or on the host."""
    if info.get("container"):
        cmd = f"docker exec -i {info['container']} sh -c {shlex.quote(cmd)}"
    return r.run(cmd, input=input, check=check)


def detect(r: Remote) -> dict | None:
    """Returns server info, or None if AmneziaWG is not set up."""
    names = r.run("command -v docker >/dev/null && docker ps --format '{{.Names}}' || true").split()
    container = next((n for n in names if n.startswith("amnezia-awg")), None)
    if container:
        base = {"mode": "amnezia", "container": container}
        confs = rx(r, base, f"ls {AMNEZIA_DIR}/*.conf").split()
        if not confs:
            raise RuntimeError(f"В контейнере {container} не найден {AMNEZIA_DIR}/*.conf")
        tool = rx(r, base, "command -v awg >/dev/null && echo awg || echo wg").strip()
        psk = rx(r, base, f"cat {AMNEZIA_DIR}/wireguard_psk.key 2>/dev/null || true").strip()
        info = {**base, "conf_path": confs[0], "tool": tool, "psk": psk or None}
    elif r.run(f"test -f {NATIVE_CONF} && echo yes || true").strip() == "yes":
        info = {"mode": "native", "container": None, "conf_path": NATIVE_CONF, "tool": "awg", "psk": None}
    else:
        return None
    info["iface"] = info["conf_path"].rsplit("/", 1)[1].removesuffix(".conf")
    return read_info(r, info)


def is_legacy(info: dict) -> bool:
    """True if the server speaks plain AmneziaWG 1.0 (no S3/S4/I*, single-number H1-H4), i.e. routers can connect."""
    for k, v in info["params"].items():
        k = k.lower()
        if k in ("s3", "s4") and str(v) == "0":
            continue
        if k not in AWG1_KEYS or (k.startswith("h") and not str(v).isdigit()):
            return False
    return True


def awg_version(info: dict) -> str:
    """Protocol version a client needs: 1.0 (routers), 2.0, or 3.x (header protection)."""
    if any(k.lower() == "headerprotectionkey" for k in info["params"]):
        return "3.x"
    return "1.0" if is_legacy(info) else "2.0"


def detect_instance(r: Remote, instance: str) -> dict | None:
    """Our own container with the given AmneziaWG version, or None if it is not running."""
    inst = INSTANCES[instance]
    names = r.run("command -v docker >/dev/null && docker ps --format '{{.Names}}' || true").split()
    if inst["container"] not in names:
        return None
    return read_info(r, {"mode": instance, "container": inst["container"], "tool": "awg", "psk": None,
                         "iface": inst["iface"], "conf_path": f"/opt/cascade/{inst['iface']}.conf"})


def detect_legacy(r: Remote) -> dict | None:
    return detect_instance(r, "legacy")


def udp_ports_in_use(r: Remote) -> set[int]:
    return set(parse_udp_listen(r.run("ss -Huln 2>/dev/null || true", check=False)))


def parse_udp_listen(text: str) -> list[int]:
    ports = set()
    for line in text.splitlines():
        cols = line.split()
        if len(cols) >= 4 and cols[3].rsplit(":", 1)[-1].isdigit():
            ports.add(int(cols[3].rsplit(":", 1)[-1]))
    return sorted(ports)


def server_conf(port: int, subnet: str, wan: str | None = None, version: str = "v1") -> str:
    lines = [
        "[Interface]",
        f"PrivateKey = {keys.gen_private_key()}",
        f"Address = {subnet}",
        f"ListenPort = {port}",
        *[f"{k} = {v}" for k, v in random_params(version).items()],
    ]
    if wan:
        lines += [
            f"PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; "
            f"iptables -t nat -A POSTROUTING -o {wan} -j MASQUERADE",
            f"PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; "
            f"iptables -t nat -D POSTROUTING -o {wan} -j MASQUERADE",
        ]
    return "\n".join(lines) + "\n"


def free_port(used: set[int]) -> int:
    return random.choice([p for p in range(30000, 60001) if p not in used])


def install_instance(r: Remote, instance: str, main: dict | None, log) -> dict:
    """Runs AmneziaWG of the requested version in its own container next to whatever is already on the server."""
    inst = INSTANCES[instance]
    ensure_docker(r, log)
    image = AWG_IMAGE
    if instance == "legacy" and main and main.get("container"):  # reuse the AmneziaVPN image, nothing to pull
        image = r.run(f"docker inspect -f '{{{{.Config.Image}}}}' {main['container']} 2>/dev/null || true").strip() or AWG_IMAGE
    port = free_port(udp_ports_in_use(r) | ({main["listen_port"]} if main else set()))
    log(f"[{r.host}] запуск {inst['label']} в контейнере {inst['container']} (образ {image}), UDP {port}")
    r.run(f"mkdir -p {inst['dir']} && chmod 700 {inst['dir']}")
    r.put(f"{inst['dir']}/{inst['iface']}.conf", server_conf(port, inst["subnet"], version=inst["version"]))
    r.put(f"{inst['dir']}/start.sh", start_script(inst), mode="700")
    r.run(f"docker rm -f {inst['container']} >/dev/null 2>&1; "
          f"docker run -d --name {inst['container']} --restart always --cap-add NET_ADMIN --device /dev/net/tun "
          f"--sysctl net.ipv4.ip_forward=1 -p {port}:{port}/udp -v {inst['dir']}:/opt/cascade "
          f"--entrypoint /bin/sh {shlex.quote(image)} /opt/cascade/start.sh >/dev/null")
    for _ in range(30):
        time.sleep(POLL_SECONDS / 5)
        if r.run(f"docker exec {inst['container']} awg show {inst['iface']} listen-port 2>/dev/null || true").strip() == str(port):
            break
    else:
        logs = r.run(f"docker logs --tail 20 {inst['container']} 2>&1", check=False)
        raise RuntimeError(f"[{r.host}] контейнер {inst['container']} не поднял {inst['iface']}:\n{logs}")
    net = ipaddress.ip_interface(inst["subnet"]).network
    if str(net) not in r.run(f"docker exec {inst['container']} iptables -t nat -S POSTROUTING 2>&1", check=False):
        logs = r.run(f"docker logs --tail 20 {inst['container']} 2>&1", check=False)
        raise RuntimeError(f"[{r.host}] в контейнере {inst['container']} не включился NAT "
                           f"(клиенты останутся без интернета):\n{logs}")
    r.run(f"if command -v ufw >/dev/null && ufw status | grep -q active; then ufw allow {port}/udp; fi")
    log(f"[{r.host}] {inst['label']} запущен на UDP {port}")
    return detect_instance(r, instance)


def install_legacy(r: Remote, main: dict, log) -> dict:
    return install_instance(r, "legacy", main, log)


def read_info(r: Remote, info: dict) -> dict:
    iface, _ = configs.parse_conf(rx(r, info, f"cat {info['conf_path']}"))
    return {
        **info,
        "listen_port": int(iface["ListenPort"]),
        "address": iface["Address"].split(",")[0].strip(),
        "public_key": keys.public_key(iface["PrivateKey"]),
        "params": configs.obfuscation_params(iface),
    }


def _header_ranges() -> list[str]:
    """Four non-overlapping H ranges (AWG 2.0+), one per bucket of the uint32 space."""
    step = (2**31 - 5) // 4
    out = []
    for i in range(4):
        lo = 5 + i * step + random.randint(0, step // 2)
        out.append(f"{lo}-{lo + random.randint(10**5, 10**7)}")
    return out


def random_params(version: str = "v1") -> dict:
    """Obfuscation parameters, per the amneziawg-go README recommendations."""
    s1 = random.randint(15, 150)
    s2 = random.choice([s for s in range(15, 151) if s != s1 and s1 + 56 != s and s + 56 != s1])
    p = {"Jc": random.randint(4, 12), "Jmin": 8, "Jmax": 80, "S1": s1, "S2": s2}
    if version == "v1":  # single-number headers, no S3/S4 — what routers understand
        h = random.sample(range(5, 2**31 - 1), 4)
        p |= {"H1": h[0], "H2": h[1], "H3": h[2], "H4": h[3]}
    else:
        p |= {"S3": random.randint(15, 150), "S4": random.randint(15, 150)}
        p |= {f"H{i}": rng for i, rng in enumerate(_header_ranges(), 1)}
    if version == "v3":  # header protection is symmetric, so clients get the same key
        p["HeaderProtectionKey"] = keys.gen_psk()
        p["ContentPaddingAddition"] = f"{random.randint(8, 32)}-{random.randint(64, 160)}"
    return p


INSTALL_UNIT = "cascade-awg-install"
INSTALL_LOG = "/var/log/cascade-awg-install.log"
INSTALL_OK = "/var/log/cascade-awg-install.ok"
INSTALL_PATH = "/root/cascade-awg-install.sh"
INSTALL_TIMEOUT = 40 * 60

# runs detached on the server (systemd-run), so a dropped SSH connection does not interrupt apt
INSTALL_SCRIPT = r"""
set -e
exec >/var/log/cascade-awg-install.log 2>&1
export DEBIAN_FRONTEND=noninteractive
apt-get() { command apt-get -o DPkg::Lock::Timeout=900 "$@"; }  # wait for a running dpkg instead of failing
. /etc/os-release
dpkg --configure -a || true
apt-get update -q
apt-get install -y -q curl gnupg iptables "linux-headers-$(uname -r)" || apt-get install -y -q curl gnupg iptables
if [ "$ID" = ubuntu ]; then
  apt-get install -y -q software-properties-common
  add-apt-repository -y ppa:amnezia/ppa
else
  FP=$(curl -fsSL https://api.launchpad.net/1.0/~amnezia/+archive/ubuntu/ppa | grep -o '"signing_key_fingerprint": *"[0-9A-F]*"' | grep -o '[0-9A-F]\{40\}')
  curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x$FP" | gpg --dearmor --yes -o /usr/share/keyrings/amnezia.gpg
  echo "deb [signed-by=/usr/share/keyrings/amnezia.gpg] https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal main" > /etc/apt/sources.list.d/amnezia.list
fi
apt-get update -q
apt-get install -y -q amneziawg
mkdir -p /etc/amnezia/amneziawg
echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-amneziawg.conf
sysctl -q -p /etc/sysctl.d/99-amneziawg.conf
touch /var/log/cascade-awg-install.ok
"""


DOCKER_SCRIPT = r"""
set -e
exec >/var/log/cascade-docker-install.log 2>&1
export DEBIAN_FRONTEND=noninteractive
apt-get() { command apt-get -o DPkg::Lock::Timeout=900 "$@"; }
dpkg --configure -a || true
apt-get update -q
apt-get install -y -q docker.io
systemctl enable --now docker
touch /var/log/cascade-docker-install.ok
"""


def run_detached(r: Remote, log, unit: str, script: str, message: str) -> None:
    """Starts (or joins an already running) detached job and waits for it, reconnecting on SSH drops."""
    ok, logfile, path = f"/var/log/{unit}.ok", f"/var/log/{unit}.log", f"/root/{unit}.sh"
    if r.run(f"systemctl is-active --quiet {unit} && echo yes || true").strip() == "yes":
        log(f"[{r.host}] {message}: уже идёт на сервере — жду завершения…")
    else:
        log(f"[{r.host}] {message}…")
        r.put(path, script, mode="700")
        r.run(f"rm -f {ok}; systemctl reset-failed {unit} 2>/dev/null; "
              f"systemd-run --unit={unit} --quiet bash {path}")
    deadline = time.monotonic() + INSTALL_TIMEOUT
    while time.monotonic() < deadline:
        time.sleep(POLL_SECONDS)
        try:
            state = r.run(f"test -f {ok} && echo ok || systemctl is-active {unit} || true", timeout=30).strip()
        except Exception as e:
            log(f"[{r.host}] связь потеряна ({e.__class__.__name__}), переподключаюсь; установка продолжается на сервере")
            try:
                r.reconnect()
            except Exception:
                pass
            continue
        if state == "ok":
            return
        if state not in ("active", "activating"):
            tail = r.run(f"tail -15 {logfile}", check=False)
            raise RuntimeError(f"[{r.host}] {message}: ошибка, лог {logfile}:\n{tail}")
    raise RuntimeError(f"[{r.host}] {message}: не завершилось за {INSTALL_TIMEOUT // 60} минут, лог {logfile}")


def run_install(r: Remote, log) -> None:
    run_detached(r, log, INSTALL_UNIT, INSTALL_SCRIPT, "установка AmneziaWG (apt, может занять 5–15 минут)")


def ensure_docker(r: Remote, log) -> None:
    if r.run("command -v docker >/dev/null && echo yes || true").strip() != "yes":
        run_detached(r, log, "cascade-docker-install", DOCKER_SCRIPT, "установка Docker")


def install_native(r: Remote, log) -> dict:
    run_install(r, log)
    wan = r.run("ip route show default | awk '{print $5; exit}'").strip()
    port = free_port(udp_ports_in_use(r))
    r.put(NATIVE_CONF, server_conf(port, NATIVE_SUBNET, wan))
    r.run(f"if command -v ufw >/dev/null && ufw status | grep -q active; then ufw allow {port}/udp; fi")
    r.run("systemctl enable --now awg-quick@awg0")
    log(f"[{r.host}] AmneziaWG запущен на UDP {port}")
    return detect(r)


def ensure(r: Remote, log) -> dict:
    info = detect(r)
    if info:
        where = f"контейнер {info['container']}" if info["container"] else "нативная установка"
        log(f"[{r.host}] найден AmneziaWG: {where}, {info['conf_path']}, UDP {info['listen_port']}")
        return info
    return install_native(r, log)


def apply_conf(r: Remote, info: dict) -> None:
    """Applies the config to the running interface without dropping other peers."""
    t = info["tool"]
    rx(r, info, f"{t}-quick strip {info['conf_path']} > /tmp/cascade-strip.conf && "
                f"{t} syncconf {info['iface']} /tmp/cascade-strip.conf; rc=$?; rm -f /tmp/cascade-strip.conf; exit $rc")


def clients_table(r: Remote, info: dict, change) -> None:
    """Edits AmneziaVPN's user list so its app shows the same clients."""
    if info["mode"] != "amnezia":
        return
    path = f"{AMNEZIA_DIR}/clientsTable"
    raw = rx(r, info, f"cat {path} 2>/dev/null || true").strip()
    table = change(json.loads(raw) if raw else [])
    rx(r, info, f"cat > {path}", input=json.dumps(table, indent=4))


def remove_peer(r: Remote, info: dict, public_key: str) -> None:
    """Revokes a client on the exit server: drops its peer and applies the config."""
    text = rx(r, info, f"cat {info['conf_path']}")
    new = configs.drop_peer(text, public_key)
    if new != text:
        rx(r, info, f"cat > {info['conf_path']}", input=new)
        apply_conf(r, info)
    clients_table(r, info, lambda t: [x for x in t if x.get("clientId") != public_key])


def peer_stats(r: Remote, info: dict) -> dict[str, dict]:
    """Per-peer counters from the running interface: {public_key: {rx, tx, handshake}}.
    Counters are reset when the interface restarts, so callers accumulate them."""
    t, iface = info["tool"], info["iface"]
    stats = {}
    for line in rx(r, info, f"{t} show {iface} transfer", check=False).splitlines():
        cols = line.split()
        if len(cols) == 3 and cols[1].isdigit():
            stats[cols[0]] = {"rx": int(cols[1]), "tx": int(cols[2]), "handshake": 0}
    for line in rx(r, info, f"{t} show {iface} latest-handshakes", check=False).splitlines():
        cols = line.split()
        if len(cols) == 2 and cols[0] in stats and cols[1].isdigit():
            stats[cols[0]]["handshake"] = int(cols[1])
    return stats


def add_peer(r: Remote, info: dict, name: str) -> dict:
    """Creates a client peer on the server and applies it without restart. Returns client key material."""
    text = rx(r, info, f"cat {info['conf_path']}")
    _, peers = configs.parse_conf(text)
    net = ipaddress.ip_interface(info["address"]).network
    used = {ipaddress.ip_interface(info["address"]).ip}
    for p in peers:
        for a in p.get("AllowedIPs", "").split(","):
            if a.strip():
                used.add(ipaddress.ip_interface(a.strip()).ip)
    ip = next((h for h in net.hosts() if h not in used), None)
    if ip is None:
        raise RuntimeError(f"[{r.host}] нет свободных IP в {net}")

    priv = keys.gen_private_key()
    client = {"private_key": priv, "public_key": keys.public_key(priv),
              "psk": info.get("psk") or keys.gen_psk(), "ip": str(ip)}
    peer = (f"\n[Peer]\n# {name}\nPublicKey = {client['public_key']}\n"
            f"PresharedKey = {client['psk']}\nAllowedIPs = {ip}/32\n")
    rx(r, info, f"cat >> {info['conf_path']}", input=peer)
    apply_conf(r, info)
    clients_table(r, info, lambda t: t + [{"clientId": client["public_key"], "userData": {
        "clientName": name,
        "creationDate": datetime.now(timezone.utc).strftime("%a %b %d %H:%M:%S %Y"),
    }}])
    return client
