//! Exit AmneziaWG server: detect the existing setup, install if missing, add/revoke clients, read traffic.
//! Port of `app/foreign.py`.
use std::collections::{HashMap, HashSet};
use std::net::Ipv4Addr;
use std::time::Duration;

use amz_core::awg::{instance as awg_instance, random_params, Instance, AWG_IMAGE};
use amz_core::model::{AwgInfo, ClientKeys};
use amz_core::{keys, parse_conf, obfuscation_params, drop_peer, pyjson};
use anyhow::{anyhow, bail, Result};
use rand::seq::SliceRandom;
use serde_json::{json, Value};

use crate::remote::{quote, Log, Remote, DEFAULT_TIMEOUT};

pub const AMNEZIA_DIR: &str = "/opt/amnezia/awg";
pub const NATIVE_CONF: &str = "/etc/amnezia/amneziawg/awg0.conf";
pub const NATIVE_SUBNET: &str = "10.8.0.1/24";
const INSTALL_TIMEOUT: Duration = Duration::from_secs(40 * 60);

/// Delay between polls of a detached job; tests run with paused tokio time.
pub const POLL: Duration = Duration::from_secs(5);

pub fn start_script(inst: &Instance) -> String {
    let net = network(inst.subnet).map(|(ip, len)| format!("{ip}/{len}")).unwrap_or_default();
    format!(
        "#!/bin/sh\n# generated by vpn_service: {label}\n\
         awg-quick down /opt/cascade/{i}.conf 2>/dev/null\n\
         awg-quick up /opt/cascade/{i}.conf\n\
         iptables -A FORWARD -i {i} -j ACCEPT\n\
         iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT\n\
         iptables -t nat -A POSTROUTING -s {net} -o eth0 -j MASQUERADE\n\
         exec tail -f /dev/null\n",
        label = inst.label, i = inst.iface,
    )
}

/// "10.9.0.1/24" -> (10.9.0.0, 24)
fn network(cidr: &str) -> Option<(Ipv4Addr, u32)> {
    let (ip, len) = cidr.trim().split_once('/').unwrap_or((cidr.trim(), "32"));
    let (ip, len): (Ipv4Addr, u32) = (ip.parse().ok()?, len.parse().ok()?);
    if len > 32 {
        return None;
    }
    let mask = if len == 0 { 0 } else { u32::MAX << (32 - len) };
    Some((Ipv4Addr::from(u32::from(ip) & mask), len))
}

/// Runs cmd inside the AWG container (if any) or on the host.
pub async fn rx<R: Remote>(r: &mut R, info: &AwgInfo, cmd: &str, input: Option<&str>, check: bool) -> Result<String> {
    let cmd = match &info.container {
        Some(c) => format!("docker exec -i {c} sh -c {}", quote(cmd)),
        None => cmd.to_string(),
    };
    r.exec(&cmd, input, check, DEFAULT_TIMEOUT).await
}

async fn containers<R: Remote>(r: &mut R) -> Result<Vec<String>> {
    Ok(r.run("command -v docker >/dev/null && docker ps --format '{{.Names}}' || true").await?
        .split_whitespace().map(String::from).collect())
}

/// The server's own AmneziaWG (AmneziaVPN container or native install), or None.
pub async fn detect<R: Remote>(r: &mut R) -> Result<Option<AwgInfo>> {
    let names = containers(r).await?;
    let mut info = if let Some(container) = names.iter().find(|n| n.starts_with("amnezia-awg")) {
        let base = AwgInfo { mode: "amnezia".into(), container: Some(container.clone()), ..Default::default() };
        let confs = rx(r, &base, &format!("ls {AMNEZIA_DIR}/*.conf"), None, true).await?;
        let conf = confs.split_whitespace().next()
            .ok_or_else(|| anyhow!("В контейнере {container} не найден {AMNEZIA_DIR}/*.conf"))?.to_string();
        let tool = rx(r, &base, "command -v awg >/dev/null && echo awg || echo wg", None, true).await?.trim().to_string();
        let psk = rx(r, &base, &format!("cat {AMNEZIA_DIR}/wireguard_psk.key 2>/dev/null || true"), None, true)
            .await?.trim().to_string();
        AwgInfo { conf_path: conf, tool, psk: Some(psk).filter(|p| !p.is_empty()), ..base }
    } else if r.run(&format!("test -f {NATIVE_CONF} && echo yes || true")).await?.trim() == "yes" {
        AwgInfo { mode: "native".into(), conf_path: NATIVE_CONF.into(), tool: "awg".into(), ..Default::default() }
    } else {
        return Ok(None);
    };
    let file = info.conf_path.rsplit('/').next().unwrap_or_default();
    info.iface = file.strip_suffix(".conf").unwrap_or(file).to_string();
    read_info(r, info).await.map(Some)
}

/// Our own container with the given AmneziaWG version ("legacy"/"v2"/"v3"), or None if it is not running.
pub async fn detect_instance<R: Remote>(r: &mut R, instance: &str) -> Result<Option<AwgInfo>> {
    let inst = awg_instance(instance).ok_or_else(|| anyhow!("Неизвестная версия AmneziaWG: {instance}"))?;
    if !containers(r).await?.iter().any(|n| n == inst.container) {
        return Ok(None);
    }
    let info = AwgInfo {
        mode: instance.into(), container: Some(inst.container.into()), tool: "awg".into(),
        iface: inst.iface.into(), conf_path: format!("/opt/cascade/{}.conf", inst.iface), ..Default::default()
    };
    read_info(r, info).await.map(Some)
}

/// "main" (the server's own AmneziaWG) or one of our instances.
pub async fn detect_any<R: Remote>(r: &mut R, instance: &str) -> Result<Option<AwgInfo>> {
    if instance == "main" { detect(r).await } else { detect_instance(r, instance).await }
}

pub async fn read_info<R: Remote>(r: &mut R, info: AwgInfo) -> Result<AwgInfo> {
    let text = rx(r, &info, &format!("cat {}", info.conf_path), None, true).await?;
    let (iface, _) = parse_conf(&text);
    let get = |k: &str| iface.get(k).ok_or_else(|| anyhow!("[{}] в {} нет {k}", r.host(), info.conf_path));
    Ok(AwgInfo {
        listen_port: get("ListenPort")?.parse()?,
        address: get("Address")?.split(',').next().unwrap_or_default().trim().to_string(),
        public_key: keys::public_key(get("PrivateKey")?)?,
        params: obfuscation_params(&iface),
        ..info
    })
}

pub fn parse_udp_listen(text: &str) -> Vec<u32> {
    let mut ports: Vec<u32> = text.lines()
        .filter_map(|l| {
            let col = l.split_whitespace().nth(3)?;
            col.rsplit(':').next()?.parse().ok()
        })
        .collect::<HashSet<_>>().into_iter().collect();
    ports.sort();
    ports
}

pub async fn udp_ports_in_use<R: Remote>(r: &mut R) -> Result<HashSet<u32>> {
    Ok(parse_udp_listen(&r.run_ok("ss -Huln 2>/dev/null || true").await?).into_iter().collect())
}

pub fn server_conf(port: u32, subnet: &str, wan: Option<&str>, version: &str) -> String {
    let mut lines = vec![
        "[Interface]".to_string(),
        format!("PrivateKey = {}", keys::gen_private_key()),
        format!("Address = {subnet}"),
        format!("ListenPort = {port}"),
    ];
    lines.extend(random_params(version).iter().map(|(k, v)| format!("{k} = {v}")));
    if let Some(wan) = wan {
        lines.push(format!("PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; \
                            iptables -t nat -A POSTROUTING -o {wan} -j MASQUERADE"));
        lines.push(format!("PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; \
                            iptables -t nat -D POSTROUTING -o {wan} -j MASQUERADE"));
    }
    lines.join("\n") + "\n"
}

pub fn free_port(used: &HashSet<u32>) -> u32 {
    let free: Vec<u32> = (30000..=60000).filter(|p| !used.contains(p)).collect();
    *free.choose(&mut rand::thread_rng()).expect("30000-60000 cannot all be busy")
}

/// Runs AmneziaWG of the requested version in its own container next to whatever is already on the server.
pub async fn install_instance<R: Remote>(r: &mut R, instance: &str, main: Option<&AwgInfo>, log: Log<'_>) -> Result<AwgInfo> {
    let inst = awg_instance(instance).ok_or_else(|| anyhow!("Неизвестная версия AmneziaWG: {instance}"))?;
    let host = r.host().to_string();
    ensure_docker(r, log).await?;
    let mut image = AWG_IMAGE.to_string();
    if let (true, Some(c)) = (instance == "legacy", main.and_then(|m| m.container.as_ref())) {
        // reuse the AmneziaVPN image, nothing to pull
        let found = r.run(&format!("docker inspect -f '{{{{.Config.Image}}}}' {c} 2>/dev/null || true")).await?;
        if !found.trim().is_empty() {
            image = found.trim().to_string();
        }
    }
    let mut used = udp_ports_in_use(r).await?;
    used.extend(main.map(|m| m.listen_port as u32));
    let port = free_port(&used);
    log(format!("[{host}] запуск {} в контейнере {} (образ {image}), UDP {port}", inst.label, inst.container));
    r.run(&format!("mkdir -p {d} && chmod 700 {d}", d = inst.dir)).await?;
    r.put(&format!("{}/{}.conf", inst.dir, inst.iface), &server_conf(port, inst.subnet, None, inst.version), "600").await?;
    r.put(&format!("{}/start.sh", inst.dir), &start_script(inst), "700").await?;
    r.run(&format!(
        "docker rm -f {c} >/dev/null 2>&1; docker run -d --name {c} --restart always --cap-add NET_ADMIN \
         --device /dev/net/tun --sysctl net.ipv4.ip_forward=1 -p {port}:{port}/udp -v {d}:/opt/cascade \
         --entrypoint /bin/sh {img} /opt/cascade/start.sh >/dev/null",
        c = inst.container, d = inst.dir, img = quote(&image))).await?;
    let mut up = false;
    for _ in 0..30 {
        tokio::time::sleep(POLL / 5).await;
        let lp = r.run(&format!("docker exec {} awg show {} listen-port 2>/dev/null || true", inst.container, inst.iface)).await?;
        if lp.trim() == port.to_string() {
            up = true;
            break;
        }
    }
    if !up {
        let tail = r.run_ok(&format!("docker logs --tail 20 {} 2>&1", inst.container)).await?;
        bail!("[{host}] контейнер {} не поднял {}:\n{tail}", inst.container, inst.iface);
    }
    let net = network(inst.subnet).map(|(ip, len)| format!("{ip}/{len}")).unwrap_or_default();
    if !r.run_ok(&format!("docker exec {} iptables -t nat -S POSTROUTING 2>&1", inst.container)).await?.contains(&net) {
        let tail = r.run_ok(&format!("docker logs --tail 20 {} 2>&1", inst.container)).await?;
        bail!("[{host}] в контейнере {} не включился NAT (клиенты останутся без интернета):\n{tail}", inst.container);
    }
    r.run(&format!("if command -v ufw >/dev/null && ufw status | grep -q active; then ufw allow {port}/udp; fi")).await?;
    log(format!("[{host}] {} запущен на UDP {port}", inst.label));
    detect_instance(r, instance).await?.ok_or_else(|| anyhow!("[{host}] {} не найден после запуска", inst.container))
}

// runs detached on the server (systemd-run), so a dropped SSH connection does not interrupt apt
pub const INSTALL_SCRIPT: &str = r#"
set -e
exec >/var/log/cascade-awg-install.log 2>&1
export DEBIAN_FRONTEND=noninteractive
apt-get() { command apt-get -o DPkg::Lock::Timeout=900 "$@"; }  # wait for a running dpkg instead of failing
. /etc/os-release
dpkg --configure -a || true
apt-get update -q
apt-get install -y -q curl gnupg iptables "linux-headers-$(uname -r)" || apt-get install -y -q curl gnupg iptables
if [ "$ID" = ubuntu ]; then
  apt-get install -y -q software-properties-common
  add-apt-repository -y ppa:amnezia/ppa
else
  FP=$(curl -fsSL https://api.launchpad.net/1.0/~amnezia/+archive/ubuntu/ppa | grep -o '"signing_key_fingerprint": *"[0-9A-F]*"' | grep -o '[0-9A-F]\{40\}')
  curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x$FP" | gpg --dearmor --yes -o /usr/share/keyrings/amnezia.gpg
  echo "deb [signed-by=/usr/share/keyrings/amnezia.gpg] https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal main" > /etc/apt/sources.list.d/amnezia.list
fi
apt-get update -q
apt-get install -y -q amneziawg
mkdir -p /etc/amnezia/amneziawg
echo 'net.ipv4.ip_forward=1' > /etc/sysctl.d/99-amneziawg.conf
sysctl -q -p /etc/sysctl.d/99-amneziawg.conf
touch /var/log/cascade-awg-install.ok
"#;

pub const DOCKER_SCRIPT: &str = r#"
set -e
exec >/var/log/cascade-docker-install.log 2>&1
export DEBIAN_FRONTEND=noninteractive
apt-get() { command apt-get -o DPkg::Lock::Timeout=900 "$@"; }
dpkg --configure -a || true
apt-get update -q
apt-get install -y -q docker.io
systemctl enable --now docker
touch /var/log/cascade-docker-install.ok
"#;

/// Starts (or joins an already running) detached job and waits for it, reconnecting on SSH drops.
pub async fn run_detached<R: Remote>(r: &mut R, log: Log<'_>, unit: &str, script: &str, message: &str) -> Result<()> {
    let (ok, logfile, path) = (format!("/var/log/{unit}.ok"), format!("/var/log/{unit}.log"), format!("/root/{unit}.sh"));
    let host = r.host().to_string();
    if r.run(&format!("systemctl is-active --quiet {unit} && echo yes || true")).await?.trim() == "yes" {
        log(format!("[{host}] {message}: уже идёт на сервере — жду завершения…"));
    } else {
        log(format!("[{host}] {message}…"));
        r.put(&path, script, "700").await?;
        r.run(&format!("rm -f {ok}; systemctl reset-failed {unit} 2>/dev/null; systemd-run --unit={unit} --quiet bash {path}")).await?;
    }
    let deadline = tokio::time::Instant::now() + INSTALL_TIMEOUT;
    while tokio::time::Instant::now() < deadline {
        tokio::time::sleep(POLL).await;
        let cmd = format!("test -f {ok} && echo ok || systemctl is-active {unit} || true");
        let state = match r.exec(&cmd, None, true, Duration::from_secs(30)).await {
            Ok(s) => s.trim().to_string(),
            Err(e) => {
                log(format!("[{host}] связь потеряна ({e}), переподключаюсь; установка продолжается на сервере"));
                let _ = r.reconnect().await;
                continue;
            }
        };
        if state == "ok" {
            return Ok(());
        }
        if state != "active" && state != "activating" {
            let tail = r.run_ok(&format!("tail -15 {logfile}")).await?;
            bail!("[{host}] {message}: ошибка, лог {logfile}:\n{tail}");
        }
    }
    bail!("[{host}] {message}: не завершилось за {} минут, лог {logfile}", INSTALL_TIMEOUT.as_secs() / 60)
}

pub async fn run_install<R: Remote>(r: &mut R, log: Log<'_>) -> Result<()> {
    run_detached(r, log, "cascade-awg-install", INSTALL_SCRIPT, "установка AmneziaWG (apt, может занять 5–15 минут)").await
}

pub async fn ensure_docker<R: Remote>(r: &mut R, log: Log<'_>) -> Result<()> {
    if r.run("command -v docker >/dev/null && echo yes || true").await?.trim() != "yes" {
        run_detached(r, log, "cascade-docker-install", DOCKER_SCRIPT, "установка Docker").await?;
    }
    Ok(())
}

pub async fn install_native<R: Remote>(r: &mut R, log: Log<'_>) -> Result<AwgInfo> {
    run_install(r, log).await?;
    let wan = r.run("ip route show default | awk '{print $5; exit}'").await?.trim().to_string();
    let port = free_port(&udp_ports_in_use(r).await?);
    r.put(NATIVE_CONF, &server_conf(port, NATIVE_SUBNET, Some(&wan), "v1"), "600").await?;
    r.run(&format!("if command -v ufw >/dev/null && ufw status | grep -q active; then ufw allow {port}/udp; fi")).await?;
    r.run("systemctl enable --now awg-quick@awg0").await?;
    log(format!("[{}] AmneziaWG запущен на UDP {port}", r.host()));
    detect(r).await?.ok_or_else(|| anyhow!("[{}] AmneziaWG не найден после установки", r.host()))
}

pub async fn ensure<R: Remote>(r: &mut R, log: Log<'_>) -> Result<AwgInfo> {
    if let Some(info) = detect(r).await? {
        let place = match &info.container {
            Some(c) => format!("контейнер {c}"),
            None => "нативная установка".into(),
        };
        log(format!("[{}] найден AmneziaWG: {place}, {}, UDP {}", r.host(), info.conf_path, info.listen_port));
        return Ok(info);
    }
    install_native(r, log).await
}

/// Applies the config to the running interface without dropping other peers.
pub async fn apply_conf<R: Remote>(r: &mut R, info: &AwgInfo) -> Result<()> {
    let t = &info.tool;
    rx(r, info, &format!(
        "{t}-quick strip {} > /tmp/cascade-strip.conf && {t} syncconf {} /tmp/cascade-strip.conf; \
         rc=$?; rm -f /tmp/cascade-strip.conf; exit $rc", info.conf_path, info.iface), None, true).await?;
    Ok(())
}

/// Edits AmneziaVPN's user list so its app shows the same clients.
async fn clients_table<R: Remote>(r: &mut R, info: &AwgInfo, change: impl FnOnce(Vec<Value>) -> Vec<Value>) -> Result<()> {
    if info.mode != "amnezia" {
        return Ok(());
    }
    let path = format!("{AMNEZIA_DIR}/clientsTable");
    let raw = rx(r, info, &format!("cat {path} 2>/dev/null || true"), None, true).await?;
    let table = if raw.trim().is_empty() { vec![] } else { serde_json::from_str(raw.trim())? };
    let text = pyjson::dumps(&Value::Array(change(table)), 4);
    rx(r, info, &format!("cat > {path}"), Some(&text), true).await?;
    Ok(())
}

/// Revokes a client on the exit server: drops its peer and applies the config.
pub async fn remove_peer<R: Remote>(r: &mut R, info: &AwgInfo, public_key: &str) -> Result<()> {
    let text = rx(r, info, &format!("cat {}", info.conf_path), None, true).await?;
    let new = drop_peer(&text, public_key);
    if new != text {
        rx(r, info, &format!("cat > {}", info.conf_path), Some(&new), true).await?;
        apply_conf(r, info).await?;
    }
    clients_table(r, info, |t| t.into_iter().filter(|x| x.get("clientId").and_then(Value::as_str) != Some(public_key)).collect()).await
}

#[derive(Debug, Clone, Copy, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PeerStat {
    pub rx: u64,
    pub tx: u64,
    pub handshake: i64,
}

/// Per-peer counters from the running interface. Counters reset when the interface restarts, so callers accumulate them.
pub async fn peer_stats<R: Remote>(r: &mut R, info: &AwgInfo) -> Result<HashMap<String, PeerStat>> {
    let (t, iface) = (&info.tool, &info.iface);
    let mut stats = HashMap::new();
    for line in rx(r, info, &format!("{t} show {iface} transfer"), None, false).await?.lines() {
        if let [pk, rx_, tx_] = line.split_whitespace().collect::<Vec<_>>()[..] {
            if let (Ok(rx_), Ok(tx_)) = (rx_.parse(), tx_.parse()) {
                stats.insert(pk.to_string(), PeerStat { rx: rx_, tx: tx_, handshake: 0 });
            }
        }
    }
    for line in rx(r, info, &format!("{t} show {iface} latest-handshakes"), None, false).await?.lines() {
        if let [pk, hs] = line.split_whitespace().collect::<Vec<_>>()[..] {
            if let (Some(s), Ok(hs)) = (stats.get_mut(pk), hs.parse()) {
                s.handshake = hs;
            }
        }
    }
    Ok(stats)
}

/// Creates a client peer on the server and applies it without restart. Returns client key material.
pub async fn add_peer<R: Remote>(r: &mut R, info: &AwgInfo, name: &str) -> Result<ClientKeys> {
    let text = rx(r, info, &format!("cat {}", info.conf_path), None, true).await?;
    let (_, peers) = parse_conf(&text);
    let (net, len) = network(&info.address).ok_or_else(|| anyhow!("[{}] непонятный адрес {}", r.host(), info.address))?;
    let own: Ipv4Addr = info.address.split('/').next().unwrap_or_default().parse()?;
    let mut used: HashSet<Ipv4Addr> = HashSet::from([own]);
    for p in &peers {
        for a in p.get("AllowedIPs").map(String::as_str).unwrap_or("").split(',') {
            if let Ok(ip) = a.trim().split('/').next().unwrap_or_default().parse() {
                used.insert(ip);
            }
        }
    }
    let size = 1u64 << (32 - len);
    let first = u32::from(net) as u64;
    // hosts() of the network: no network/broadcast address, except for /31 and /32
    let hosts = if len >= 31 { first..first + size } else { first + 1..first + size - 1 };
    let ip = hosts.map(|h| Ipv4Addr::from(h as u32)).find(|h| !used.contains(h))
        .ok_or_else(|| anyhow!("[{}] нет свободных IP в {net}/{len}", r.host()))?;

    let private_key = keys::gen_private_key();
    let client = ClientKeys {
        public_key: keys::public_key(&private_key)?,
        private_key,
        psk: Some(info.psk.clone().unwrap_or_else(keys::gen_psk)),
        ip: ip.to_string(),
    };
    let psk = client.psk.as_deref().unwrap_or_default();
    let peer = format!("\n[Peer]\n# {name}\nPublicKey = {}\nPresharedKey = {psk}\nAllowedIPs = {ip}/32\n", client.public_key);
    rx(r, info, &format!("cat >> {}", info.conf_path), Some(&peer), true).await?;
    apply_conf(r, info).await?;
    let created = chrono::Utc::now().format("%a %b %d %H:%M:%S %Y").to_string();
    let entry = json!({"clientId": client.public_key, "userData": {"clientName": name, "creationDate": created}});
    clients_table(r, info, |mut t| { t.push(entry); t }).await?;
    Ok(client)
}
